"""add file model

Revision ID: c2d2a370740b
Revises: 8250f8aeae41
Create Date: 2025-11-20 08:34:43.850553

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2d2a370740b"
down_revision: Union[str, None] = "8250f8aeae41"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("stored_name", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("path", sa.String(length=500), nullable=False),
        sa.Column("uploaded_by_user_id", sa.Integer(), nullable=True),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"], ["users.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_files_content_type", "files", ["content_type"], unique=False)
    op.create_index(
        "idx_files_deleted_cleanup", "files", ["is_deleted", "deleted_at"], unique=False
    )
    op.create_index(
        "idx_files_file_id_active", "files", ["file_id", "is_deleted"], unique=False
    )
    op.create_index(
        "idx_files_uploaded_by_user",
        "files",
        ["uploaded_by_user_id", "is_deleted"],
        unique=False,
    )
    op.create_index(op.f("ix_files_file_id"), "files", ["file_id"], unique=True)
    op.create_index(op.f("ix_files_id"), "files", ["id"], unique=False)
    op.create_index(
        op.f("ix_files_uploaded_by_user_id"),
        "files",
        ["uploaded_by_user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_files_uploaded_by_user_id"), table_name="files")
    op.drop_index(op.f("ix_files_id"), table_name="files")
    op.drop_index(op.f("ix_files_file_id"), table_name="files")
    op.drop_index("idx_files_uploaded_by_user", table_name="files")
    op.drop_index("idx_files_file_id_active", table_name="files")
    op.drop_index("idx_files_deleted_cleanup", table_name="files")
    op.drop_index("idx_files_content_type", table_name="files")
    op.drop_table("files")
    # ### end Alembic commands ###
