"""add chunk unique contraint

Revision ID: cc88bbf67c60
Revises: 8ac40f727013
Create Date: 2025-10-26 17:05:19.271502

"""
from typing import Sequence, Union

import sqlalchemy as sa  # noqa: F401

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cc88bbf67c60"
down_revision: Union[str, None] = "8ac40f727013"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "ux_chunk_doc_index", "chunks", ["document_id", "chunk_index"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ux_chunk_doc_index", "chunks", type_="unique")
    # ### end Alembic commands ###
